version: '3.9'

services:
  
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ramos
    ports:
      - "5454:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
      
  redis_clasic_lru:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_clasic_lru_data:/data
    environment:
      - REDIS_PASSWORD=tilines
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru"]

volumes:
  db_data:
  redis_clasic_lru_data:
