services:
  redis-clasic-mru:
    image: 'bitnami/redis:7.0.4-debian-11-r23'
    expose:
      - '6379'
    networks:
      ipv4_network:
        ipv4_address: 172.18.0.2
    environment:
      - REDIS_PASSWORD=master1234
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory-policy allkeys-random --maxmemory 2mb

  postgresql:
    image: postgres
    container_name: pgdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ramos
    ports:
      - "5454:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

networks:
  ipv4_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

volumes:
  db_data: {}

