services:
  redis-clasic-lru:
    image: 'bitnami/redis:7.0.4-debian-11-r23'
    expose:
      - '6379'
    environment:
      - REDIS_PASSWORD=master1234
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory-policy volatile-ttl --maxmemory 2mb

  postgresql:
    image: postgres
    container_name: pgdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ramos
    ports:
      - "5454:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  db_data: {}
