services:
  redis-master:
    image: 'bitnami/redis:7.0.4-debian-11-r23'
    expose:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=master1234
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory-policy allkeys-lfu --maxmemory 5mb
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.2

  redis-replica-uno:
    image: 'bitnami/redis:7.0.4-debian-11-r23'
    expose:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=master1234
      - REDIS_PASSWORD=replica1234
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory-policy allkeys-lfu --maxmemory 5mb
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.3

  redis-replica-dos:
    image: 'bitnami/redis:7.0.4-debian-11-r23'
    expose:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=master1234
      - REDIS_PASSWORD=replica1234
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory-policy allkeys-lfu --maxmemory 5mb
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.4

  postgresql:
    image: postgres
    container_name: pgdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ramos
    ports:
      - "5454:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../../db-init:/docker-entrypoint-initdb.d
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.10

networks:
  redis_cluster_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.18.0.0/16

volumes:
  redis_1_data: {}
  redis_2_data: {}
  redis_3_data: {}
  db_data: {}
